spring.application.name=lilyluz-api
server.port=8080

# Base de datos persistente en la carpeta del proyecto (creará un archivo lilyluzdb.mv.db)
spring.datasource.url=jdbc:h2:file:./data/lilyluzdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate (Spring Boot 3 usa Jakarta)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true